#+title: Project West Lake

* 背景
Project West Lake是DWeb Shanghai为配合网络社会研究所的年会的网状网络主题，而进行的一系列活动。更具体的说，是为了实现下面两个具体的目标：

+ 年会上的网状网Workshop；
+ 年会期间运行一个小规模的网状网，并该在网络运行具体特色的应用。

在年会前，需要进行一些准备工作，包括硬件评估，选型，和生产，软件的研发，workshop的准备以及排练，以及相关的文档工作。

* 网状网Workshop

网状网Workshop的内容是让参与者实践网状网的组网。参与者需要自行购买（或者我们预先购买一些）一款支持最新版本OpenWRT，且Wifi驱动支持802.11s模式（mesh模式）的无线路由器，并且携带笔记本。Workshop过程中，指导参与者对路由器进行配置，使所有的路由器作为一个网状网的节点。最后通过某种方式，验证节点之间是能够互相连通的，或者在该临时组好的网状网上运行应用，供大家访问。

下面是workshop具体的一些步骤，方便起见，假定节点为HLK-7628N模块，其他型号的根据实际情况进行调整：

** 背景介绍
+ 自由软件、开源
+ OpenWRT（来源）
+ OpenMesh
** 准备工作
+ 携带过来的路由器应该已经更新为最新版本的OpenWRT(19.07);
+ 确认是否[[https://openwrt.org/docs/guide-user/network/wifi/mesh/batman#does_your_device_support_80211s_or_ibss][支持mesh模式]]；
+ OpenWRT配置为AP模式，且自行选一个不容易重名的ESSID；
+ 笔记本安装ssh客户端。
+ 路由器需要接入到互联网，主要有2个方案：
  - 通过Wifi上网，笔记本通过有线和路由器直连；
  - 通过有线上网，笔记本通过Wifi和路由器连接；
** 安装软件
在路由器能访问互联网的情况下，执行下列命令：
#+begin_src sh
opkg update
opkg install kmod-batman-adv

opkg install batctl-full

opkg remove wpad-basic
opkg install wpad-mesh-openssl
#+end_src

** TODO 配置
下面是大致的配置，待补充细节：

+ 添加mesh模式的Wifi网络接口（network interface）
  - Wifi设备的配置
  - 网络接口的配置
+ 配置batman-adv的网络接口
+ 配置LAN
  + batman-adv的网络接口的桥接
  + 分配固定IP
+ 删除客户模式（如果有），添加AP模式（如果需要）
+ DHCP相关配置（待定）

** TODO 测试
- ping
- dhcp
- 运行应用

** 参考
+ https://www.open-mesh.org/projects/open-mesh/wiki
+ https://openwrt.org/docs/guide-user/network/wifi/mesh/batman

* TODO 小规模网状网的部署和运行
